# SwiftLint Configuration for QualiaKit

# Disable rules that conflict with our code style
disabled_rules:
  - trailing_comma
  - todo
  - line_length # We use a custom line length

# Opt-in rules
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - sorted_first_last
  - modifier_order
  - redundant_nil_coalescing
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - fallthrough
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - multiline_parameters
  - overridden_super_call
  - private_action
  - private_outlet
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# File and folder exclusions
excluded:
  - .build
  - .swiftpm
  - Tests/QualiaKitTests/Resources
  - DerivedData

# Customized rules
file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - i
    - j
    - k
    - id
    - x
    - y
    - z

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 15
  error: 25

# Nesting
nesting:
  type_level:
    warning: 2

# Force unwrapping and implicitly unwrapped optionals allowed in tests
force_unwrapping:
  excluded:
    - Tests/**/*.swift

implicitly_unwrapped_optional:
  excluded:
    - Tests/**/*.swift

# Custom rules
custom_rules:
  # Prefer using `isEmpty` over `count == 0`
  empty_count_check:
    name: "Empty Count"
    regex: '\.count\s*==\s*0'
    message: "Use `isEmpty` instead of comparing `count` to 0"
    severity: warning

# Reporter type
reporter: "xcode"
