"""Independent stdlib arithmetic oracle and manually specified tokenization vectors."""
import math


def cases():
    # Content IDs are explicitly reviewed fixtures, not generated by the Swift tokenizer.
    return [
        {'id': 'single', 'text': 'quiet', 'content': [4]},
        {'id': 'ascii-case', 'text': 'STORM rises', 'content': [5, 6]},
        {'id': 'whitespace', 'text': ' \tquiet\r\nstorm\vfalls\f ', 'content': [4, 5, 7]},
        {'id': 'unicode-preserved', 'text': 'café CAFÉ 🙂', 'content': [8, 1, 10]},
        {'id': 'punctuation-preserved', 'text': 'storm! quiet.', 'content': [11, 1]},
        {'id': 'unknown', 'text': 'unlisted', 'content': [1]},
        {'id': 'non-ascii-space', 'text': 'quiet\u00a0storm', 'content': [1]},
        {'id': 'combining-mark-after-space', 'text': 'quiet \u0301 storm', 'content': [4, 1, 5]},
        {'id': 'truncated', 'text': 'quiet storm rises falls quiet storm rises falls quiet', 'content': [4, 5, 6, 7, 4, 5, 6, 7, 4]},
        {'id': 'exact-boundary', 'text': 'quiet storm rises falls', 'content': [4, 5, 6, 7]},
    ]


def expected(case, length, roles, probability, independent):
    content = case['content'][:length - 2]
    ids = [2] + content + [3] + [0] * (length - 2 - len(content))
    mask = [1] * (len(content) + 2) + [0] * (length - 2 - len(content))
    sums = {'tokenIDs': sum((i + 1) * value for i, value in enumerate(ids)),
            'attentionMask': sum((i + 1) * value for i, value in enumerate(mask)), 'tokenTypeIDs': 0}
    a, b, c = 0.0, 0.25, -0.5
    if 'tokenIDs' in roles.values():
        a += sums['tokenIDs'] / 32; b -= sums['tokenIDs'] / 64; c += sums['tokenIDs'] / 128
    if 'attentionMask' in roles.values():
        a += sums['attentionMask'] / 16; b += sums['attentionMask'] / 8; c -= sums['attentionMask'] / 16
    logits = [a, b, c]
    if independent:
        scores = [1 / (1 + math.exp(-x)) for x in logits]
    else:
        exp = [math.exp(x - max(logits)) for x in logits]
        scores = [x / sum(exp) for x in exp]
    return dict(id=case['id'], text=case['text'], ids=ids, mask=mask,
                truncatedCount=max(0, len(case['content']) - (length - 2)),
                raw=scores if probability else logits, scores=scores)
